/*英语*/ 
$("#english").click(function(){
    $(".link:nth(0)").text("Ultraman");
    $(".link:nth(1)").text("Female role");
    $(".link:nth(2)").text("One Piece");
    $(".link:nth(3)").text("military");
    $(".link:nth(4)").text("translate");
    $(".link-second:nth(0)").text("Ranking of comprehensive strength");
    $(".link-second:nth(1)").text("Fighting strength ranking");
    $(".link-second:nth(2)").text("AV actresses ranking");
    $(".link-second:nth(3)").text("Idol ranking");
    $(".link-second:nth(4)").text("Actresses ranking");
    $(".link-second:nth(5)").text("Character strength ranking");
    $("#english").text("English");
    $("#chinese").text("Chinese");
    $("#japanese").text("Japanese");
    $("#pills-home-tab").text("Ultraman comprehensive strength ranking");
    $("#pills-profile-tab").text("Ultraman Fighting ability ranking");
    $("#avv").text("AV actress");
    $("#idoll").text("idol");
    $("#joyuu").text("Actress");
    $("#one").text("Character strength ranking");
    $(".tip").text("The characters that have appeared ranking of Peak strength");
    $(".army").text("Global Comprehensive military strength");
    $(".air").text("Global Air power");
    $(".earth").text("Global Army strength");
    $(".h-navy").text("Global Nucleus navy strength");
    $(".c-navy").text("Global Conventional Navy strength");
    $("h5:nth(0)").text("NO.1 United States of America");
    $("h5:nth(1)").text("NO.2 Russia");
    $("h5:nth(2)").text("NO.3 China");
    $("h5:nth(3)").text("NO.4 India");
    $("h5:nth(4)").text("NO.5 France");
    $("h5:nth(5)").text("NO.6 Japan");
    $("h5:nth(6)").text("NO.7 South Korea");
    $("h5:nth(7)").text("NO.8 United Kingdom");
    $("h5:nth(8)").text("NO.9 Turkey");
    $("h5:nth(9)").text("NO.10 Germany");
    $("h5:nth(10)").text("NO.1 United States Air Force");
    $("h5:nth(11)").text("NO.2 United States Naval air force");
    $("h5:nth(12)").text("NO.3 United States National Guard Air Force");
    $("h5:nth(13)").text("NO.4 Snouteslands Royal Air Force");
    $("h5:nth(14)").text("NO.5 Israeli Air force");
    $("h5:nth(15)").text("NO.6 Russian Air Force");
    $("h5:nth(16)").text("NO.7 British Royal Air Force");
    $("h5:nth(17)").text("NO.8 French Air Force");
    $("h5:nth(18)").text("NO.9 PLA Air Force");
    $("h5:nth(19)").text("NO.10 Japan Air Self Defense Force");
    $("h5:nth(20)").text("NO.11 Bundeswehr Air force");
    $("h5:nth(21)").text("NO.12 Indian Air Force");
    $("h5:nth(22)").text("NO.13 South Korean Air Force");
    $("h5:nth(23)").text("NO.14 Turkish Air Force");
    $("h5:nth(24)").text("NO.1 United States Army");
    $("h5:nth(25)").text("NO.2 PLA Army");
    $("h5:nth(26)").text("NO.3 Russian Ground Forces");
    $("h5:nth(27)").text("NO.4 Indian Army");
    $("h5:nth(28)").text("NO.5 French Army");
    $("h5:nth(29)").text("NO.6 British Army");
    $("h5:nth(30)").text("NO.7 German Federal defense army");
    $("h5:nth(31)").text("NO.8 Japan's land self defense force");
    $("h5:nth(32)").text("NO.9 Turkish army");
    $("h5:nth(33)").text("NO.10 Republic of Korea Army");
    $("h5:nth(34)").text("NO.1 US Navy");
    $("h5:nth(35)").text("NO.2 Russian Navy");
    $("h5:nth(36)").text("NO.3 British Royal Navy");
    $("h5:nth(37)").text("NO.4 French Navy");
    $("h5:nth(38)").text("NO.5 PLA Navy");
    $("h5:nth(39)").text("NO.6 Indian Navy");
    $("h5:nth(40)").text("NO.1 US Navy");
    $("h5:nth(41)").text("NO.2 PLA Navy");
    $("h5:nth(42)").text("NO.3 Russian Navy");
    $("h5:nth(43)").text("NO.4 Japan Maritime Self Defense Force");
    $("h5:nth(44)").text("NO.5 French Navy");
    $("h5:nth(45)").text("NO.6 British Royal Navy");
    $("h5:nth(46)").text("NO.7 Italy Navy");
    $("h5:nth(47)").text("NO.8 Indian Navy");
    $("h5:nth(48)").text("NO.9 South Korean Navy");
    $("h5:nth(49)").text("NO.10 Royal Australian Navy");

});
/*移动端-英文*/ 
$("#s5").click(function(){
    $("#s1").text("Ultraman");
    $("#s2").text("Female role");
    $("#s3").text("One Piece");
    $("#s4").text("military");
    $("#s5").text("English");
    $("#s6").text("Chinese");
    $("#s7").text("Japanese");
    $("#pills-home-tab").text("Ultraman comprehensive strength ranking");
    $("#pills-profile-tab").text("Ultraman Fighting ability ranking");
    $("#avv").text("AV actress");
    $("#idoll").text("idol");
    $("#joyuu").text("Actress");
    $("#one").text("Character strength ranking");
    $(".tip").text("The characters that have appeared ranking of Peak strength");
    $(".army").text("Global Comprehensive military strength");
    $(".air").text("Global Air power");
    $(".earth").text("Global Army strength");
    $(".h-navy").text("Global Nucleus navy strength");
    $(".c-navy").text("Global Conventional Navy strength");
    $("h5:nth(0)").text("NO.1 United States of America");
    $("h5:nth(1)").text("NO.2 Russia");
    $("h5:nth(2)").text("NO.3 China");
    $("h5:nth(3)").text("NO.4 India");
    $("h5:nth(4)").text("NO.5 France");
    $("h5:nth(5)").text("NO.6 Japan");
    $("h5:nth(6)").text("NO.7 South Korea");
    $("h5:nth(7)").text("NO.8 United Kingdom");
    $("h5:nth(8)").text("NO.9 Turkey");
    $("h5:nth(9)").text("NO.10 Germany");
    $("h5:nth(10)").text("NO.1 United States Air Force");
    $("h5:nth(11)").text("NO.2 United States Naval air force");
    $("h5:nth(12)").text("NO.3 United States National Guard Air Force");
    $("h5:nth(13)").text("NO.4 Snouteslands Royal Air Force");
    $("h5:nth(14)").text("NO.5 Israeli Air force");
    $("h5:nth(15)").text("NO.6 Russian Air Force");
    $("h5:nth(16)").text("NO.7 British Royal Air Force");
    $("h5:nth(17)").text("NO.8 French Air Force");
    $("h5:nth(18)").text("NO.9 PLA Air Force");
    $("h5:nth(19)").text("NO.10 Japan Air Self Defense Force");
    $("h5:nth(20)").text("NO.11 Bundeswehr Air force");
    $("h5:nth(21)").text("NO.12 Indian Air Force");
    $("h5:nth(22)").text("NO.13 South Korean Air Force");
    $("h5:nth(23)").text("NO.14 Turkish Air Force");
    $("h5:nth(24)").text("NO.1 United States Army");
    $("h5:nth(25)").text("NO.2 PLA Army");
    $("h5:nth(26)").text("NO.3 Russian Ground Forces");
    $("h5:nth(27)").text("NO.4 Indian Army");
    $("h5:nth(28)").text("NO.5 French Army");
    $("h5:nth(29)").text("NO.6 British Army");
    $("h5:nth(30)").text("NO.7 German Federal defense army");
    $("h5:nth(31)").text("NO.8 Japan's land self defense force");
    $("h5:nth(32)").text("NO.9 Turkish army");
    $("h5:nth(33)").text("NO.10 Republic of Korea Army");
    $("h5:nth(34)").text("NO.1 US Navy");
    $("h5:nth(35)").text("NO.2 Russian Navy");
    $("h5:nth(36)").text("NO.3 British Royal Navy");
    $("h5:nth(37)").text("NO.4 French Navy");
    $("h5:nth(38)").text("NO.5 PLA Navy");
    $("h5:nth(39)").text("NO.6 Indian Navy");
    $("h5:nth(40)").text("NO.1 US Navy");
    $("h5:nth(41)").text("NO.2 PLA Navy");
    $("h5:nth(42)").text("NO.3 Russian Navy");
    $("h5:nth(43)").text("NO.4 Japan Maritime Self Defense Force");
    $("h5:nth(44)").text("NO.5 French Navy");
    $("h5:nth(45)").text("NO.6 British Royal Navy");
    $("h5:nth(46)").text("NO.7 Italy Navy");
    $("h5:nth(47)").text("NO.8 Indian Navy");
    $("h5:nth(48)").text("NO.9 South Korean Navy");
    $("h5:nth(49)").text("NO.10 Royal Australian Navy");
});
/*中文*/ 
$("#chinese").click(function(){
    $(".link:nth(0)").text("奥特曼排名");
    $(".link:nth(1)").text("女性角色排名");
    $(".link:nth(2)").text("海贼王排名");
    $(".link:nth(3)").text("军事排名");
    $(".link:nth(4)").text("语种切换");
    $(".link-second:nth(0)").text("单体奥特曼综合实力排名");
    $(".link-second:nth(1)").text("单体奥特曼格斗能力排名");
    $(".link-second:nth(2)").text("av女优排名");
    $(".link-second:nth(3)").text("偶像排名");
    $(".link-second:nth(4)").text("女演员排名");
    $(".link-second:nth(5)").text("海贼王人物实力排名");
    $("#english").text("英语");
    $("#chinese").text("中文");
    $("#japanese").text("日语");
    $("#pills-home-tab").text("单体奥特曼综合实力排名");
    $("#pills-profile-tab").text("单体奥特曼格斗能力排名");
    $("#avv").text("AV 女演员");
    $("#idoll").text("偶像");
    $("#joyuu").text("女演员");
    $("#one").text("海贼王人物实力排名");
    $(".tip").text("已登场人物目前巅峰实力排名");
    $(".army").text("全球综合军力排名");
    $(".air").text("全球空中力量排名");
    $(".earth").text("全球陆军实力排名");
    $(".h-navy").text("全球核海军实力排名");
    $(".c-navy").text("全球常规海军实力排名");
    $("h5:nth(0)").text("NO.1 美国");
    $("h5:nth(1)").text("NO.2 俄罗斯");
    $("h5:nth(2)").text("NO.3 中国");
    $("h5:nth(3)").text("NO.4 印度");
    $("h5:nth(4)").text("NO.5 法国");
    $("h5:nth(5)").text("NO.6 日本");
    $("h5:nth(6)").text("NO.7 韩国");
    $("h5:nth(7)").text("NO.8 英国");
    $("h5:nth(8)").text("NO.9 土耳其");
    $("h5:nth(9)").text("NO.10 德国");
    $("h5:nth(10)").text("NO.1 美国空军");
    $("h5:nth(11)").text("NO.2 美国海军航空兵");
    $("h5:nth(12)").text("NO.3 美国国名警卫队空军");
    $("h5:nth(13)").text("NO.4 南岛皇家空军");
    $("h5:nth(14)").text("NO.5 以色列空军");
    $("h5:nth(15)").text("NO.6 俄罗斯空军");
    $("h5:nth(16)").text("NO.7 英国皇家空军");
    $("h5:nth(17)").text("NO.8 法国空军");
    $("h5:nth(18)").text("NO.9 中国人民解放军空军");
    $("h5:nth(19)").text("NO.10 日本航空自卫队");
    $("h5:nth(20)").text("NO.11 德国联邦国防军空军");
    $("h5:nth(21)").text("NO.12 印度空军");
    $("h5:nth(22)").text("NO.13 韩国空军");
    $("h5:nth(23)").text("NO.14 土耳其空军");
    $("h5:nth(24)").text("NO.1 美国陆军");
    $("h5:nth(25)").text("NO.2 中国人民解放军陆军");
    $("h5:nth(26)").text("NO.3 俄罗斯陆军");
    $("h5:nth(27)").text("NO.4 印度陆军");
    $("h5:nth(28)").text("NO.5 法国陆军");
    $("h5:nth(29)").text("NO.6 英国陆军");
    $("h5:nth(30)").text("NO.7 德国联邦国防军陆军");
    $("h5:nth(31)").text("NO.8 日本陆上自卫队");
    $("h5:nth(32)").text("NO.9 土耳其陆军");
    $("h5:nth(33)").text("NO.10 大韩民国陆军");
    $("h5:nth(34)").text("NO.1 美国海军");
    $("h5:nth(35)").text("NO.2 俄罗斯海军");
    $("h5:nth(36)").text("NO.3 英国皇家海军");
    $("h5:nth(37)").text("NO.4 法国海军");
    $("h5:nth(38)").text("NO.5 中国人民解放军海军");
    $("h5:nth(39)").text("NO.6 印度海军");
    $("h5:nth(40)").text("NO.1 美国海军");
    $("h5:nth(41)").text("NO.2 中国人民解放军海军");
    $("h5:nth(42)").text("NO.3 俄罗斯海军");
    $("h5:nth(43)").text("NO.4 日本海上自卫队");
    $("h5:nth(44)").text("NO.5 法国海军");
    $("h5:nth(45)").text("NO.6 英国皇家海军");
    $("h5:nth(46)").text("NO.7 意大利海军");
    $("h5:nth(47)").text("NO.8 印度海军");
    $("h5:nth(48)").text("NO.9 韩国海军");
    $("h5:nth(49)").text("NO.10 澳大利亚皇家海军");
});
/*移动端-中文*/
$("#s6").click(function(){
    $("#s1").text("奥特曼");
    $("#s2").text("女性角色");
    $("#s3").text("海贼王");
    $("#s4").text("军事");
    $("#s5").text("英语");
    $("#s6").text("中文");
    $("#s7").text("日语");
    $("#pills-home-tab").text("单体奥特曼综合实力排名");
    $("#pills-profile-tab").text("单体奥特曼格斗能力排名");
    $("#avv").text("AV 女演员");
    $("#idoll").text("偶像");
    $("#joyuu").text("女演员");
    $("#one").text("海贼王人物实力排名");
    $(".tip").text("已登场人物目前巅峰实力排名");
    $(".army").text("全球综合军力排名");
    $(".air").text("全球空中力量排名");
    $(".earth").text("全球陆军实力排名");
    $(".h-navy").text("全球核海军实力排名");
    $(".c-navy").text("全球常规海军实力排名");
    $("h5:nth(0)").text("NO.1 美国");
    $("h5:nth(1)").text("NO.2 俄罗斯");
    $("h5:nth(2)").text("NO.3 中国");
    $("h5:nth(3)").text("NO.4 印度");
    $("h5:nth(4)").text("NO.5 法国");
    $("h5:nth(5)").text("NO.6 日本");
    $("h5:nth(6)").text("NO.7 韩国");
    $("h5:nth(7)").text("NO.8 英国");
    $("h5:nth(8)").text("NO.9 土耳其");
    $("h5:nth(9)").text("NO.10 德国");
    $("h5:nth(10)").text("NO.1 美国空军");
    $("h5:nth(11)").text("NO.2 美国海军航空兵");
    $("h5:nth(12)").text("NO.3 美国国名警卫队空军");
    $("h5:nth(13)").text("NO.4 南岛皇家空军");
    $("h5:nth(14)").text("NO.5 以色列空军");
    $("h5:nth(15)").text("NO.6 俄罗斯空军");
    $("h5:nth(16)").text("NO.7 英国皇家空军");
    $("h5:nth(17)").text("NO.8 法国空军");
    $("h5:nth(18)").text("NO.9 中国人民解放军空军");
    $("h5:nth(19)").text("NO.10 日本航空自卫队");
    $("h5:nth(20)").text("NO.11 德国联邦国防军空军");
    $("h5:nth(21)").text("NO.12 印度空军");
    $("h5:nth(22)").text("NO.13 韩国空军");
    $("h5:nth(23)").text("NO.14 土耳其空军");
    $("h5:nth(24)").text("NO.1 美国陆军");
    $("h5:nth(25)").text("NO.2 中国人民解放军陆军");
    $("h5:nth(26)").text("NO.3 俄罗斯陆军");
    $("h5:nth(27)").text("NO.4 印度陆军");
    $("h5:nth(28)").text("NO.5 法国陆军");
    $("h5:nth(29)").text("NO.6 英国陆军");
    $("h5:nth(30)").text("NO.7 德国联邦国防军陆军");
    $("h5:nth(31)").text("NO.8 日本陆上自卫队");
    $("h5:nth(32)").text("NO.9 土耳其陆军");
    $("h5:nth(33)").text("NO.10 大韩民国陆军");
    $("h5:nth(34)").text("NO.1 美国海军");
    $("h5:nth(35)").text("NO.2 俄罗斯海军");
    $("h5:nth(36)").text("NO.3 英国皇家海军");
    $("h5:nth(37)").text("NO.4 法国海军");
    $("h5:nth(38)").text("NO.5 中国人民解放军海军");
    $("h5:nth(39)").text("NO.6 印度海军");
    $("h5:nth(40)").text("NO.1 美国海军");
    $("h5:nth(41)").text("NO.2 中国人民解放军海军");
    $("h5:nth(42)").text("NO.3 俄罗斯海军");
    $("h5:nth(43)").text("NO.4 日本海上自卫队");
    $("h5:nth(44)").text("NO.5 法国海军");
    $("h5:nth(45)").text("NO.6 英国皇家海军");
    $("h5:nth(46)").text("NO.7 意大利海军");
    $("h5:nth(47)").text("NO.8 印度海军");
    $("h5:nth(48)").text("NO.9 韩国海军");
    $("h5:nth(49)").text("NO.10 澳大利亚皇家海军");
});
/*日语*/ 
$("#japanese").click(function(){
    $(".link:nth(0)").text("ウルトラマン");
    $(".link:nth(1)").text("女性キャラクター");
    $(".link:nth(2)").text("ワンピース");
    $(".link:nth(3)").text("軍事");
    $(".link:nth(4)").text("言語切り替え");
    $(".link-second:nth(0)").text("総合力ランキング");
    $(".link-second:nth(1)").text("格闘能力ランキング");
    $(".link-second:nth(2)").text("AV女優ランキング");
    $(".link-second:nth(3)").text("アイドルランキング");
    $(".link-second:nth(4)").text("女優ランキング");
    $(".link-second:nth(5)").text("人物の実力");
    $("#english").text("英語");
    $("#chinese").text("中国語");
    $("#japanese").text("日本語");
    $("#pills-home-tab").text("単体ウルトラマン総合力");
    $("#pills-profile-tab").text("単体ウルトラマン格闘能力");
    $("#avv").text("av女優");
    $("#idoll").text("アイドル");
    $("#joyuu").text("女優");
    $("#one").text("人物の実力のランキング");
    $(".tip").text("すでに登場した人物のトップ実力ランキング");
    $(".army").text("世界総合軍事力ランキング");
    $(".air").text("空中実力ランキング");
    $(".earth").text("陸軍実力ランキング");
    $(".h-navy").text("核海軍実力ランキング");
    $(".c-navy").text("一般海軍実力ランキング");
    $("h5:nth(0)").text("NO.1 米国");
    $("h5:nth(1)").text("NO.2 ロシア");
    $("h5:nth(2)").text("NO.3 中国");
    $("h5:nth(3)").text("NO.4 インド");
    $("h5:nth(4)").text("NO.5 フランス");
    $("h5:nth(5)").text("NO.6 日本");
    $("h5:nth(6)").text("NO.7 韓国");
    $("h5:nth(7)").text("NO.8 イギリス");
    $("h5:nth(8)").text("NO.9 トルコ");
    $("h5:nth(9)").text("NO.10 ドイツ");
    $("h5:nth(10)").text("NO.1 米国空軍");
    $("h5:nth(11)").text("NO.2 米国海軍航空兵");
    $("h5:nth(12)").text("NO.3 米国国名警備隊空軍");
    $("h5:nth(13)").text("NO.4 南島王立空軍");
    $("h5:nth(14)").text("NO.5 イスラエル空軍");
    $("h5:nth(15)").text("NO.6 ロシア空軍");
    $("h5:nth(16)").text("NO.7 イギリス王立空軍");
    $("h5:nth(17)").text("NO.8 フランス空軍");
    $("h5:nth(18)").text("NO.9 中国人民解放軍空軍");
    $("h5:nth(19)").text("NO.10 日本航空自衛隊");
    $("h5:nth(20)").text("NO.11 ドイツ連邦国防軍空軍");
    $("h5:nth(21)").text("NO.12 インド空軍");
    $("h5:nth(22)").text("NO.13 韓国空軍");
    $("h5:nth(23)").text("NO.14 トルコ空軍");
    $("h5:nth(24)").text("NO.1 米国陸軍");
    $("h5:nth(25)").text("NO.2 中国人民解放軍陸軍");
    $("h5:nth(26)").text("NO.3 ロシア陸軍");
    $("h5:nth(27)").text("NO.4 インド陸軍");
    $("h5:nth(28)").text("NO.5 フランス陸軍");
    $("h5:nth(29)").text("NO.6 イギリス陸軍");
    $("h5:nth(30)").text("NO.7 ドイツ連邦国防軍陸軍");
    $("h5:nth(31)").text("NO.8 日本陸上自衛隊");
    $("h5:nth(32)").text("NO.9 トルコ陸軍");
    $("h5:nth(33)").text("NO.10 大韓民国陸軍");
    $("h5:nth(34)").text("NO.1 米国海軍");
    $("h5:nth(35)").text("NO.2 ロシア海軍");
    $("h5:nth(36)").text("NO.3 イギリス王立海軍");
    $("h5:nth(37)").text("NO.4 フランス海軍");
    $("h5:nth(38)").text("NO.5 中国人民解放軍海軍");
    $("h5:nth(39)").text("NO.6 インド海軍");
    $("h5:nth(40)").text("NO.1 米国海軍");
    $("h5:nth(41)").text("NO.2 中国人民解放軍海軍");
    $("h5:nth(42)").text("NO.3 ロシア海軍");
    $("h5:nth(43)").text("NO.4 日本海上自衛隊");
    $("h5:nth(44)").text("NO.5 フランス海軍");
    $("h5:nth(45)").text("NO.6 イギリス王立海軍");
    $("h5:nth(46)").text("NO.7 イタリア海軍");
    $("h5:nth(47)").text("NO.8 インド海軍");
    $("h5:nth(48)").text("NO.9 韓国海軍");
    $("h5:nth(49)").text("NO.10 オーストラリア王立海軍");
});
/*移动端-日文*/ 
$("#s7").click(function(){
    $("#s1").text("ウルトラマン");
    $("#s2").text("女性キャラクター");
    $("#s3").text("ワンピース");
    $("#s4").text("軍事");
    $("#s5").text("英語");
    $("#s6").text("中国語");
    $("#s7").text("日本語");
    $("#pills-home-tab").text("単体ウルトラマン総合力");
    $("#pills-profile-tab").text("単体ウルトラマン格闘能力");
    $("#avv").text("av女優");
    $("#idoll").text("アイドル");
    $("#joyuu").text("女優");
    $("#one").text("人物の実力のランキング");
    $(".tip").text("すでに登場した人物のトップ実力ランキング");
    $(".army").text("世界総合軍事力ランキング");
    $(".air").text("空中実力ランキング");
    $(".earth").text("陸軍実力ランキング");
    $(".h-navy").text("核海軍実力ランキング");
    $(".c-navy").text("一般海軍実力ランキング");
    $("h5:nth(0)").text("NO.1 米国");
    $("h5:nth(1)").text("NO.2 ロシア");
    $("h5:nth(2)").text("NO.3 中国");
    $("h5:nth(3)").text("NO.4 インド");
    $("h5:nth(4)").text("NO.5 フランス");
    $("h5:nth(5)").text("NO.6 日本");
    $("h5:nth(6)").text("NO.7 韓国");
    $("h5:nth(7)").text("NO.8 イギリス");
    $("h5:nth(8)").text("NO.9 トルコ");
    $("h5:nth(9)").text("NO.10 ドイツ");
    $("h5:nth(10)").text("NO.1 米国空軍");
    $("h5:nth(11)").text("NO.2 米国海軍航空兵");
    $("h5:nth(12)").text("NO.3 米国国名警備隊空軍");
    $("h5:nth(13)").text("NO.4 南島王立空軍");
    $("h5:nth(14)").text("NO.5 イスラエル空軍");
    $("h5:nth(15)").text("NO.6 ロシア空軍");
    $("h5:nth(16)").text("NO.7 イギリス王立空軍");
    $("h5:nth(17)").text("NO.8 フランス空軍");
    $("h5:nth(18)").text("NO.9 中国人民解放軍空軍");
    $("h5:nth(19)").text("NO.10 日本航空自衛隊");
    $("h5:nth(20)").text("NO.11 ドイツ連邦国防軍空軍");
    $("h5:nth(21)").text("NO.12 インド空軍");
    $("h5:nth(22)").text("NO.13 韓国空軍");
    $("h5:nth(23)").text("NO.14 トルコ空軍");
    $("h5:nth(24)").text("NO.1 米国陸軍");
    $("h5:nth(25)").text("NO.2 中国人民解放軍陸軍");
    $("h5:nth(26)").text("NO.3 ロシア陸軍");
    $("h5:nth(27)").text("NO.4 インド陸軍");
    $("h5:nth(28)").text("NO.5 フランス陸軍");
    $("h5:nth(29)").text("NO.6 イギリス陸軍");
    $("h5:nth(30)").text("NO.7 ドイツ連邦国防軍陸軍");
    $("h5:nth(31)").text("NO.8 日本陸上自衛隊");
    $("h5:nth(32)").text("NO.9 トルコ陸軍");
    $("h5:nth(33)").text("NO.10 大韓民国陸軍");
    $("h5:nth(34)").text("NO.1 米国海軍");
    $("h5:nth(35)").text("NO.2 ロシア海軍");
    $("h5:nth(36)").text("NO.3 イギリス王立海軍");
    $("h5:nth(37)").text("NO.4 フランス海軍");
    $("h5:nth(38)").text("NO.5 中国人民解放軍海軍");
    $("h5:nth(39)").text("NO.6 インド海軍");
    $("h5:nth(40)").text("NO.1 米国海軍");
    $("h5:nth(41)").text("NO.2 中国人民解放軍海軍");
    $("h5:nth(42)").text("NO.3 ロシア海軍");
    $("h5:nth(43)").text("NO.4 日本海上自衛隊");
    $("h5:nth(44)").text("NO.5 フランス海軍");
    $("h5:nth(45)").text("NO.6 イギリス王立海軍");
    $("h5:nth(46)").text("NO.7 イタリア海軍");
    $("h5:nth(47)").text("NO.8 インド海軍");
    $("h5:nth(48)").text("NO.9 韓国海軍");
    $("h5:nth(49)").text("NO.10 オーストラリア王立海軍");
});